export enum urlEnums {
    createUser = '/user/create',
    updateUser = '/user/update',
    loginURL = '/user/login',
    deleteUser = '/user/delete',
    userList = '/user/list',
    getUser = '/user/get',
    addDriver = '/driver/add',
    getDriver = '/driver/get',
    updateDriver = '/driver/update',
    driverList = '/driver/list',
    deleteDriver = '/driver/delete',
    addSupplier = '/supplier/add',
    supplierList = '/supplier/list',
    updateSupplier = '/supplier/update',
    deleteSupplier = '/supplier/delete',
    getSupplier = '/supplier/get',
    addFarm = '/farm/add',
    getPermission = '/permission/get',
    updatePermission = '/permission/update',
    addPermission = '/permission/add',
    deletePermission = '/permission/delete',
    getUserPermission = '/userPermission/get',
    updateUserPermission = '/userPermission/update',
    deleteUserPErmission = '/userPermission/delete',
    addUserPermission = '/userPermission/add'
}